package com.nestedinfinity.mod.microverse;

import com.nestedinfinity.mod.NestedInfinity;
import com.nestedinfinity.mod.fluids.NIFluids;
import com.nestedinfinity.mod.items.NICircuits;
import com.nestedinfinity.mod.items.NIItems;
import com.nestedinfinity.mod.items.NIOpticalItems;
import dev.emi.emi.api.EmiEntrypoint;
import dev.emi.emi.api.EmiPlugin;
import dev.emi.emi.api.EmiRegistry;
import dev.emi.emi.api.recipe.EmiInfoRecipe;
import dev.emi.emi.api.recipe.EmiRecipe;
import dev.emi.emi.api.recipe.EmiRecipeCategory;
import dev.emi.emi.api.render.EmiTexture;
import dev.emi.emi.api.stack.EmiIngredient;
import dev.emi.emi.api.stack.EmiStack;
import dev.emi.emi.api.widget.WidgetHolder;
import java.util.ArrayList;
import java.util.List;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.Font;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.ItemTags;
import net.minecraft.util.FormattedCharSequence;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.material.Fluids;

/**
 * EMI integration for the microverse program: a graphical recipe page per
 * universe matter tier (what the projector consumes and yields) and per
 * singularity (what the catalyzer grows from a plain MI singularity seed
 * plus its catalyst), plus an info page on the heart.
 *
 * <p>EMI discovers this class through the {@link EmiEntrypoint} annotation
 * and is its only referencer, so the mod runs fine without EMI installed.
 */
@EmiEntrypoint
public final class MicroverseEmiPlugin implements EmiPlugin {
    private static final int TEXT_COLOR = 0x3F3F3F;

    public static final EmiRecipeCategory PROJECTOR = new EmiRecipeCategory(
            id("microverse_projector"), EmiStack.of(MicroverseBlocks.MICROVERSE_PROJECTOR.get()));
    public static final EmiRecipeCategory CATALYZER = new EmiRecipeCategory(
            id("singularity_catalyzer"), EmiStack.of(MicroverseBlocks.SINGULARITY_CATALYZER.get()));
    public static final EmiRecipeCategory STRUCTURE = new EmiRecipeCategory(
            id("projector_structure"), EmiStack.of(MicroverseBlocks.NEUTRONIUM_MACHINE_CASING.get()));
    public static final EmiRecipeCategory HARVESTER = new EmiRecipeCategory(
            id("microverse_harvester"), EmiStack.of(MicroverseItems.MICROVERSE_HARVESTER.get()));

    @Override
    public void register(EmiRegistry registry) {
        registry.addCategory(PROJECTOR);
        registry.addCategory(CATALYZER);
        registry.addCategory(STRUCTURE);
        registry.addCategory(HARVESTER);
        registry.addWorkstation(PROJECTOR, EmiStack.of(MicroverseBlocks.MICROVERSE_PROJECTOR.get()));
        registry.addWorkstation(CATALYZER, EmiStack.of(MicroverseBlocks.SINGULARITY_CATALYZER.get()));
        registry.addWorkstation(STRUCTURE, EmiStack.of(MicroverseBlocks.MICROVERSE_PROJECTOR.get()));
        registry.addWorkstation(HARVESTER, EmiStack.of(miItem("assembler")));
        registry.addWorkstation(HARVESTER, EmiStack.of(MicroverseBlocks.MICROVERSE_PROJECTOR.get()));
        for (int page = 0; page < 3; page++) {
            registry.addRecipe(new StructureRecipe(page));
        }
        registry.addRecipe(new HarvesterRecipe(0));
        registry.addRecipe(new HarvesterRecipe(1));
        for (int tier = 1; tier <= MicroverseItems.MATTERS.size(); tier++) {
            registry.addRecipe(new ProjectorRecipe(tier));
        }
        for (int i = 0; i < MicroverseItems.SINGULARITIES.size(); i++) {
            registry.addRecipe(new CatalyzerRecipe(i));
        }
        registry.addRecipe(new EmiInfoRecipe(
                List.of(EmiStack.of(MicroverseItems.HEART_OF_A_NONEXISTENT_WORLD.get())),
                List.of(Component.translatable("emi.mi_nested_infinity.heart.line1"),
                        Component.translatable("emi.mi_nested_infinity.heart.line2")),
                id("heart_of_a_nonexistent_world")));
    }

    /**
     * The multiblock itself, paginated into its own category. EMI caps one
     * page at roughly 210px, so the content is split instead of shrunk:
     * page 0 shows the assembled oblique (xie-er-ce) projection with a
     * legend, page 1 the exploded layout where every part is readable, and
     * page 2 the per-layer build checklist. Both diagrams are generated by
     * tools/gen_microverse_assets.py from the same layout
     * MicroverseStructure validates.
     */
    private static final class StructureRecipe implements EmiRecipe {
        private static final int WIDTH = 168;
        private static final int TEXT_X = 6;
        private static final int TEXT_WIDTH = WIDTH - 2 * TEXT_X;
        private static final int LINE_HEIGHT = 10;
        /** Keep the four numbers in sync with the generator's cropped PNGs. */
        private static final int OBLIQUE_W = 121;
        private static final int OBLIQUE_H = 80;
        private static final int EXPLODED_W = 89;
        private static final int EXPLODED_H = 134;

        private static final EmiTexture OBLIQUE = new EmiTexture(
                id("textures/gui/emi/projector_structure_oblique.png"),
                0, 0, OBLIQUE_W, OBLIQUE_H, OBLIQUE_W, OBLIQUE_H, OBLIQUE_W, OBLIQUE_H);
        private static final EmiTexture EXPLODED = new EmiTexture(
                id("textures/gui/emi/projector_structure_exploded.png"),
                0, 0, EXPLODED_W, EXPLODED_H, EXPLODED_W, EXPLODED_H, EXPLODED_W, EXPLODED_H);

        private final int page;
        private final EmiStack controller = EmiStack.of(MicroverseBlocks.MICROVERSE_PROJECTOR.get());
        private final List<EmiIngredient> inputs;

        StructureRecipe(int page) {
            this.page = page;
            List<EmiIngredient> in = new ArrayList<>();
            in.add(controller);
            // 37 base plate + 9 core + 4 forced pillars
            in.add(EmiStack.of(MicroverseBlocks.NEUTRONIUM_MACHINE_CASING.get(), 50));
            in.add(EmiStack.of(MicroverseBlocks.TDUS.get(4).get(), 4));
            in.add(EmiIngredient.of(MicroverseBlocks.COREFLAMES.stream()
                    .map(block -> (EmiIngredient) EmiStack.of(block.get())).toList()));
            this.inputs = List.copyOf(in);
        }

        @Override
        public EmiRecipeCategory getCategory() {
            return STRUCTURE;
        }

        @Override
        public ResourceLocation getId() {
            String tail = switch (page) {
                case 0 -> "assembled";
                case 1 -> "exploded";
                default -> "layers";
            };
            return id("projector_structure/" + tail);
        }

        @Override
        public List<EmiIngredient> getInputs() {
            return inputs;
        }

        @Override
        public List<EmiStack> getOutputs() {
            return List.of();
        }

        @Override
        public int getDisplayWidth() {
            return WIDTH;
        }

        @Override
        public int getDisplayHeight() {
            Font font = Minecraft.getInstance().font;
            return switch (page) {
                case 0 -> 4 + OBLIQUE_H + 8 + 18 + 3
                        + lines(font, "legend") * LINE_HEIGHT + 4
                        + lines(font, "note") * LINE_HEIGHT + 2
                        + lines(font, "hatch") * LINE_HEIGHT + 5;
                case 1 -> 4 + EXPLODED_H + 8 + lines(font, "hint") * LINE_HEIGHT + 5;
                default -> layerPageHeight(font);
            };
        }

        @Override
        public boolean supportsRecipeTree() {
            return false; // a multiblock, not a craftable recipe
        }

        @Override
        public void addWidgets(WidgetHolder widgets) {
            switch (page) {
                case 0 -> addAssembledWidgets(widgets);
                case 1 -> addExplodedWidgets(widgets);
                default -> addLayerWidgets(widgets);
            }
        }

        private void addAssembledWidgets(WidgetHolder widgets) {
            widgets.addTexture(OBLIQUE, (WIDTH - OBLIQUE_W) / 2, 4);
            int y = 4 + OBLIQUE_H + 8;
            widgets.addSlot(controller, 12, y);
            widgets.addSlot(EmiStack.of(MicroverseBlocks.TDUS.get(4).get(), 4), 54, y);
            widgets.addSlot(EmiStack.of(MicroverseBlocks.NEUTRONIUM_MACHINE_CASING.get(), 50), 96, y);
            widgets.addSlot(EmiStack.of(MicroverseBlocks.COREFLAMES.get(1).get()), 138, y);
            y += 18 + 3;
            // one wrapped legend line under the slot row — per-slot labels
            // collided at this pitch in English, so the slot order carries it
            y = addWrappedText(widgets, "legend", y) + 4;
            y = addWrappedText(widgets, "note", y) + 2;
            addWrappedText(widgets, "hatch", y);
        }

        private void addExplodedWidgets(WidgetHolder widgets) {
            widgets.addTexture(EXPLODED, (WIDTH - EXPLODED_W) / 2, 4);
            addWrappedText(widgets, "hint", 4 + EXPLODED_H + 8);
        }

        private void addLayerWidgets(WidgetHolder widgets) {
            int y = 4;
            y = addWrappedText(widgets, "bottom", y) + 3;
            widgets.addSlot(EmiStack.of(MicroverseBlocks.NEUTRONIUM_MACHINE_CASING.get(), 37),
                    (WIDTH - 18) / 2, y);
            y += 18 + 6;
            y = addWrappedText(widgets, "middle", y) + 3;
            for (int row = 0; row < 2; row++) { // the twelve flames, six per row
                for (int j = 0; j < 6; j++) {
                    widgets.addSlot(EmiStack.of(MicroverseBlocks.COREFLAMES.get(row * 6 + j).get()),
                            (WIDTH - 6 * 18) / 2 + j * 18, y);
                }
                y += 18 + 2;
            }
            widgets.addSlot(EmiStack.of(MicroverseBlocks.TDUS.get(4).get(), 4), 66, y);
            widgets.addSlot(EmiStack.of(MicroverseBlocks.NEUTRONIUM_MACHINE_CASING.get(), 9), 84, y);
            y += 18 + 6;
            y = addWrappedText(widgets, "top", y) + 3;
            widgets.addSlot(controller, 66, y);
            widgets.addSlot(EmiStack.of(MicroverseBlocks.NEUTRONIUM_MACHINE_CASING.get(), 4), 84, y);
        }

        /** The same vertical flow as {@link #addLayerWidgets}, without the widgets. */
        private static int layerPageHeight(Font font) {
            int y = 4;
            y += lines(font, "bottom") * LINE_HEIGHT + 3 + 18 + 6;
            y += lines(font, "middle") * LINE_HEIGHT + 3 + 18 + 2 + 18 + 2 + 18 + 6;
            y += lines(font, "top") * LINE_HEIGHT + 3 + 18;
            return y + 5;
        }

        private static int addWrappedText(WidgetHolder widgets, String key, int y) {
            for (FormattedCharSequence line : Minecraft.getInstance().font.split(text(key), TEXT_WIDTH)) {
                widgets.addText(line, TEXT_X, y, TEXT_COLOR, false);
                y += LINE_HEIGHT;
            }
            return y;
        }

        private static int lines(Font font, String key) {
            return font.split(text(key), TEXT_WIDTH).size();
        }

        private static Component text(String key) {
            return Component.translatable("emi.mi_nested_infinity.structure." + key);
        }
    }

    /**
     * The harvester program as its own two-page category: page 0 mirrors
     * the real assembler recipe (a quadcopter bill of materials in
     * neutronium, see NIRecipeProvider), page 1 the projector launch — the
     * drone plus 32 transuranic batteries into a running universe,
     * infinitium and the damaged wreck back out.
     */
    private static final class HarvesterRecipe implements EmiRecipe {
        private static final int WIDTH = 168;
        private static final int TEXT_X = 6;
        private static final int TEXT_WIDTH = WIDTH - 2 * TEXT_X;
        private static final int LINE_HEIGHT = 10;

        private final int page; // 0 build, 1 launch
        private final List<EmiIngredient> inputs;
        private final List<EmiStack> outputs;

        HarvesterRecipe(int page) {
            this.page = page;
            if (page == 0) {
                this.inputs = List.of(
                        EmiStack.of(miItem("neutronium_plate"), 4), // the monocoque frame
                        EmiStack.of(NIOpticalItems.LARGE_ELITE_MOTOR.get(), 4), // four brushless outrunners
                        EmiStack.of(NICircuits.OPTICAL_CIRCUIT.get()), // the flight controller
                        EmiStack.of(Items.RECOVERY_COMPASS), // the GNSS return-to-launch module
                        EmiStack.of(NIItems.GRAPHENE_ROD.get(), 4), // CFRP propellers
                        EmiStack.of(NIOpticalItems.FFKM_SHEET.get(), 2), // weather seals
                        EmiStack.of(NIFluids.MOLTEN_NEUTRONIUM.source.get(), 288)); // die-cast frame joints
                this.outputs = List.of(EmiStack.of(MicroverseItems.MICROVERSE_HARVESTER.get()));
            } else {
                this.inputs = List.of(
                        EmiStack.of(MicroverseItems.MICROVERSE_HARVESTER.get()),
                        EmiStack.of(NIItems.TRANSURANIC_BATTERY.get(),
                                MicroverseProjectorBlockEntity.HARVEST_BATTERIES));
                this.outputs = List.of(
                        EmiStack.of(MicroverseItems.INFINITIUM.get(), MicroverseProjectorBlockEntity.HARVEST_YIELD),
                        EmiStack.of(MicroverseItems.DAMAGED_MICROVERSE_HARVESTER.get()));
            }
        }

        @Override
        public EmiRecipeCategory getCategory() {
            return HARVESTER;
        }

        @Override
        public ResourceLocation getId() {
            return id("microverse_harvester/" + (page == 0 ? "build" : "launch"));
        }

        @Override
        public List<EmiIngredient> getInputs() {
            return inputs;
        }

        @Override
        public List<EmiStack> getOutputs() {
            return outputs;
        }

        @Override
        public int getDisplayWidth() {
            return WIDTH;
        }

        @Override
        public int getDisplayHeight() {
            Font font = Minecraft.getInstance().font;
            if (page == 0) {
                return 48 + lines("harvester.build.note1", font) * LINE_HEIGHT + 2
                        + lines("harvester.build.note2", font) * LINE_HEIGHT + 5;
            }
            return 50 + (lines("harvester.launch.time", font)
                    + lines("harvester.launch.return", font)
                    + lines("harvester.launch.warn", font)) * LINE_HEIGHT + 4 + 5;
        }

        @Override
        public boolean supportsRecipeTree() {
            return false; // the real assembler recipe carries the tree; the launch is projector magic
        }

        @Override
        public void addWidgets(WidgetHolder widgets) {
            if (page == 0) {
                for (int i = 0; i < 4; i++) {
                    widgets.addSlot(inputs.get(i), 6 + i * 18, 4);
                }
                for (int i = 0; i < 3; i++) { // props, seals, molten neutronium
                    widgets.addSlot(inputs.get(4 + i), 6 + i * 18, 24);
                }
                widgets.addFillingArrow(78, 22, 20000);
                widgets.addSlot(outputs.getFirst(), 114, 22);
                int y = addWrapped(widgets, "harvester.build.note1", 48) + 2;
                addWrapped(widgets, "harvester.build.note2", y);
                return;
            }
            widgets.addSlot(inputs.get(0), 30, 8);
            widgets.addSlot(inputs.get(1), 48, 8);
            widgets.addFillingArrow(80, 12, 20000);
            widgets.addSlot(outputs.get(0), 112, 8);
            widgets.addSlot(outputs.get(1), 112, 26);
            int y = addWrapped(widgets, "harvester.launch.time", 50) + 2;
            y = addWrapped(widgets, "harvester.launch.return", y) + 2;
            addWrapped(widgets, "harvester.launch.warn", y);
        }

        private static int addWrapped(WidgetHolder widgets, String key, int y) {
            for (FormattedCharSequence line : Minecraft.getInstance().font.split(text(key), TEXT_WIDTH)) {
                widgets.addText(line, TEXT_X, y, TEXT_COLOR, false);
                y += LINE_HEIGHT;
            }
            return y;
        }

        private static int lines(String key, Font font) {
            return font.split(text(key), TEXT_WIDTH).size();
        }

        private static Component text(String key) {
            return Component.translatable("emi.mi_nested_infinity." + key);
        }
    }

    /**
     * The multiblock ceremony drawn as itself: the twelve
     * singularities orbit the heart in a ring (drawn bare, without slot
     * wells, so the circle stays tight), a vertical arrow condenses them
     * downward into the matter, and the corner holds the ring's time
     * dilation units.
     */
    private static final class ProjectorRecipe implements EmiRecipe {
        private static final int WIDTH = 176;
        private static final int HEIGHT = 213;
        private static final int RING_RADIUS = 45;

        /** A 32x24 texture: outlined arrow at u=0, filled arrow at u=16. */
        private static final EmiTexture ARROW_EMPTY = new EmiTexture(
                id("textures/gui/emi/vertical_arrow.png"), 0, 0, 16, 24, 16, 24, 32, 24);
        private static final EmiTexture ARROW_FULL = new EmiTexture(
                id("textures/gui/emi/vertical_arrow.png"), 16, 0, 16, 24, 16, 24, 32, 24);

        private final int tier;
        private final List<EmiIngredient> inputs;
        private final EmiStack output;

        ProjectorRecipe(int tier) {
            this.tier = tier;
            List<EmiIngredient> in = new ArrayList<>();
            in.add(EmiStack.of(MicroverseItems.HEART_OF_A_NONEXISTENT_WORLD.get()));
            in.add(EmiStack.of(MicroverseBlocks.TDUS.get(tier - 1).get(), 4)); // the ring holds four
            for (var kind : MicroverseItems.SINGULARITIES) {
                in.add(EmiStack.of(kind.item().get()));
            }
            this.inputs = List.copyOf(in);
            int baseTicks = MicroverseProjectorBlockEntity.baseTicks(tier);
            int perRun = tier * tier + baseTicks / MicroverseProjectorBlockEntity.ITEM_INTERVAL_TICKS;
            this.output = EmiStack.of(MicroverseItems.MATTERS.get(tier - 1).get(), perRun);
        }

        @Override
        public EmiRecipeCategory getCategory() {
            return PROJECTOR;
        }

        @Override
        public ResourceLocation getId() {
            return id("microverse_projector/t" + tier);
        }

        @Override
        public List<EmiIngredient> getInputs() {
            return inputs;
        }

        @Override
        public List<EmiStack> getOutputs() {
            return List.of(output);
        }

        @Override
        public int getDisplayWidth() {
            return WIDTH;
        }

        @Override
        public int getDisplayHeight() {
            return HEIGHT;
        }

        @Override
        public boolean supportsRecipeTree() {
            return false; // a multiblock ceremony, not a craftable recipe
        }

        @Override
        public void addWidgets(WidgetHolder widgets) {
            int cx = WIDTH / 2;
            int cy = 64;
            // the ring: one bare singularity per position, starting at the top and
            // going clockwise — no slot wells, so the circle reads as twelve sparks
            for (int i = 0; i < MicroverseItems.SINGULARITIES.size(); i++) {
                double angle = Math.toRadians(i * 30 - 90);
                int x = Math.round(cx + RING_RADIUS * (float) Math.cos(angle)) - 9;
                int y = Math.round(cy + RING_RADIUS * (float) Math.sin(angle)) - 9;
                widgets.addSlot(inputs.get(2 + i), x, y).drawBack(false);
            }
            widgets.addSlot(inputs.getFirst(), cx - 9, cy - 9); // the heart holds the center
            widgets.addTexture(ARROW_EMPTY, cx - 8, 124);
            widgets.addAnimatedTexture(ARROW_FULL, cx - 8, 124, 20000, false, false, false);
            widgets.addSlot(output, cx - 9, 152);
            // bottom-left corner: the ring's time dilation units
            widgets.addSlot(inputs.get(1), 6, 152);
            int seconds = MicroverseProjectorBlockEntity.baseTicks(tier) / 20;
            widgets.addText(Component.translatable("emi.mi_nested_infinity.projector.time", seconds),
                    6, 180, TEXT_COLOR, false);
            widgets.addText(Component.translatable("emi.mi_nested_infinity.projector.rate", tier * tier),
                    6, 191, TEXT_COLOR, false);
            widgets.addText(Component.translatable("emi.mi_nested_infinity.projector.energy"),
                    6, 202, TEXT_COLOR, false);
        }
    }

    /** The catalyzer: a plain MI singularity + the kind's catalyst + its ritual -> 1 singularity of the kind. */
    private static final class CatalyzerRecipe implements EmiRecipe {
        private static final int WIDTH = 168;
        private static final int TEXT_X = 6;
        /** Long ritual texts wrap to this width instead of overflowing the page. */
        private static final int TEXT_WIDTH = WIDTH - 2 * TEXT_X;
        private static final int TEXT_Y = 44;
        private static final int LINE_HEIGHT = 10;
        private static final int GROUP_GAP = 3;

        private final int index;
        private final EmiStack seed;
        private final EmiStack catalyst;
        private final EmiStack output;
        private final Component time;
        private final Component condition;
        private final Component mode;

        CatalyzerRecipe(int index) {
            this.index = index;
            var singularity = MicroverseItems.SINGULARITIES.get(index);
            var item = SingularityCatalyzerBlockEntity.catalysts().get(index);
            long amount = Math.min(SingularityCatalyzerBlockEntity.CRAFT_AMOUNT,
                    new net.minecraft.world.item.ItemStack(item).getMaxStackSize());
            this.seed = EmiStack.of(SingularityCatalyzerBlockEntity.miSingularity());
            this.catalyst = EmiStack.of(item, amount);
            this.output = EmiStack.of(singularity.item().get(), SingularityCatalyzerBlockEntity.OUTPUT_AMOUNT);
            this.time = Component.translatable("emi.mi_nested_infinity.catalyzer.time");
            this.condition = Component.translatable(
                    "emi.mi_nested_infinity.catalyzer.condition." + singularity.key());
            this.mode = Component.translatable("emi.mi_nested_infinity.catalyzer."
                    + (eventRitual(index) ? "once" : "state"));
        }

        /** A few graphical hints of what the ritual involves (icons only). */
        private static List<EmiIngredient> ritualIcons(int index) {
            return switch (index) {
                case 0 -> List.of(EmiStack.of(Fluids.LAVA, 1000), EmiStack.of(Fluids.LAVA, 1000)); // two faces
                case 1 -> List.of(EmiIngredient.of(ItemTags.LOGS), EmiIngredient.of(ItemTags.LEAVES));
                case 2 -> List.of(EmiStack.of(Items.BONE)); // a death nearby
                case 3 -> List.of(EmiStack.of(Items.CANDLE), EmiStack.of(Items.TORCH),
                        EmiStack.of(Items.CAMPFIRE)); // the snuffable flames
                case 4 -> List.of(EmiStack.of(Items.GOLD_BLOCK)); // spirited away unseen
                case 5 -> List.of(EmiStack.of(Items.BEDROCK)); // the world floor
                case 6 -> List.of(EmiStack.of(Items.SPYGLASS)); // open sky at the top
                case 7 -> List.of(EmiStack.of(Items.SEA_LANTERN)); // light >= 13
                case 8 -> List.of(EmiStack.of(Items.BOW)); // struck by an arrow
                case 9 -> List.of(EmiIngredient.of(java.util.Arrays.asList( // four different kinds
                        EmiStack.of(Items.STONE), EmiStack.of(Items.GRANITE), EmiStack.of(Items.DIORITE),
                        EmiStack.of(Items.ANDESITE), EmiStack.of(Items.DEEPSLATE), EmiStack.of(Items.TUFF))));
                case 10 -> List.of(EmiIngredient.of(ItemTags.RAILS));
                case 11 -> List.of(EmiIngredient.of(ItemTags.DOORS));
                default -> List.of();
            };
        }

        @Override
        public EmiRecipeCategory getCategory() {
            return CATALYZER;
        }

        @Override
        public ResourceLocation getId() {
            return id("singularity_catalyzer/" + MicroverseItems.SINGULARITIES.get(index).key());
        }

        @Override
        public List<EmiIngredient> getInputs() {
            return List.of(seed, catalyst);
        }

        @Override
        public List<EmiStack> getOutputs() {
            return List.of(output);
        }

        @Override
        public int getDisplayWidth() {
            return WIDTH;
        }

        @Override
        public int getDisplayHeight() {
            Font font = Minecraft.getInstance().font;
            // every group wraps on its own — the time line wraps too in English,
            // and a hardcoded count clipped the page's last line in game
            int lines = font.split(time, TEXT_WIDTH).size()
                    + font.split(condition, TEXT_WIDTH).size()
                    + font.split(mode, TEXT_WIDTH).size();
            return TEXT_Y + lines * LINE_HEIGHT + 2 * GROUP_GAP + 5;
        }

        @Override
        public boolean supportsRecipeTree() {
            return false; // the ritual is the real ingredient
        }

        @Override
        public void addWidgets(WidgetHolder widgets) {
            widgets.addSlot(seed, 38, 0);
            widgets.addTexture(EmiTexture.PLUS, 56, 2);
            widgets.addSlot(catalyst, 69, 0);
            widgets.addFillingArrow(87, 1, 20000);
            widgets.addSlot(output, 111, 0);
            List<EmiIngredient> icons = ritualIcons(index);
            for (int i = 0; i < icons.size(); i++) {
                widgets.addSlot(icons.get(i), 6 + i * 18, 22);
            }
            int y = addWrappedText(widgets, time, TEXT_X, TEXT_Y) + GROUP_GAP;
            y = addWrappedText(widgets, condition, TEXT_X, y) + GROUP_GAP;
            addWrappedText(widgets, mode, TEXT_X, y);
        }

        /**
         * EMI's text widget draws one line as-is, so long strings simply
         * overflow the page — split with the vanilla font first. Returns the y
         * below the block; keep {@link #getDisplayHeight} in sync.
         */
        private static int addWrappedText(WidgetHolder widgets, Component text, int x, int y) {
            for (FormattedCharSequence line : Minecraft.getInstance().font.split(text, TEXT_WIDTH)) {
                widgets.addText(line, x, y, TEXT_COLOR, false);
                y += LINE_HEIGHT;
            }
            return y;
        }

        private static boolean eventRitual(int index) {
            return index == SingularityCatalyzerBlockEntity.KIND_SHADOW
                    || index == SingularityCatalyzerBlockEntity.KIND_JUSTICE
                    || index == SingularityCatalyzerBlockEntity.KIND_WHIMSY
                    || index == SingularityCatalyzerBlockEntity.KIND_FURY;
        }
    }

    private static ResourceLocation id(String path) {
        return ResourceLocation.fromNamespaceAndPath(NestedInfinity.MODID, path);
    }

    /** Registry lookup for MI items — always resolved at call time, never
     *  cached in a static initializer (see the singularity AIR lesson). */
    private static Item miItem(String path) {
        return BuiltInRegistries.ITEM.get(ResourceLocation.fromNamespaceAndPath("modern_industrialization", path));
    }

    public MicroverseEmiPlugin() {}
}
